
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-recoms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-recoms
  template:
    metadata:
      labels:
        app: chat-recoms
    spec:
      containers:
        - name: chat-recoms
          image: us-central1-docker.pkg.dev/ayoba-183a7/gcf-artifacts/chat-recoms:latest
          ports:
            - containerPort: 8000
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          volumeMounts:
            - name: gcp-sa-key
              mountPath: /var/secrets/google
              readOnly: true
            - name: log-volume
              mountPath: /app/logs
      volumes:
        - name: gcp-sa-key
          secret:
            secretName: gcp-sa-key
       
